name: Despliegue continuo

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build application
        run: |
          cd frontend
          docker build -t docker build -t FinalHia:v2 .

      - name: Stop previous container
        run: docker stop prueba || true

      - name: Remove previous container
        run: docker rm prueba || true

      - name: Run updated container
        run: |
          docker run -d --name prueba -p 4200:4200 tpfinal
